baseURL = 'https://dusky-peak.netlify.app/'
languageCode = 'cs-CZ'
title = 'Dusky Peak'

[params]
titlePrefix = "Dusky Peak | "
copyright = "Copyright © 2023 Dusky Peak"
maintainer = "ethere4labyss"

[markup]
[markup.tableOfContents]
endLevel = 2
ordered = false
startLevel = 1
